# Generated by Django 5.0.1 on 2024-01-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('total_quantity', models.IntegerField()),
                ('available_quantity', models.IntegerField()),
                ('issued', models.BooleanField()),
            ],
        ),
    ]
