# Generated by Django 5.0.1 on 2024-01-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_issuedgoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('regno', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=15)),
                ('no_issued', models.IntegerField()),
                ('date_of_issue', models.DateField()),
                ('time_of_issue', models.TimeField()),
                ('returned', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
