# Generated by Django 5.0.1 on 2024-01-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_borrower_equipment_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentlog',
            name='penalty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
